stages:
  - build
  - publish

variables:
  PUBLIC_REGISTRY_HOST: docker.io
  PUBLIC_REGISTRY_OWNER: novermore26
  PUBLIC_REGISTRY_APP_NAME: test_project
  IMAGE_NAME: $PUBLIC_REGISTRY_HOST/$PUBLIC_REGISTRY_OWNER/$PUBLIC_REGISTRY_APP_NAME

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$DOCKER_HUB_PASSWORD" $PUBLIC_REGISTRY_HOST
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

build_image_latest:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$DOCKER_HUB_PASSWORD" $PUBLIC_REGISTRY_HOST
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
