name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # реагирует на любой пуш

env:
  PUBLIC_REGISTRY_HOST: docker.io
  PUBLIC_REGISTRY_OWNER: novermore26
  PUBLIC_REGISTRY_APP_NAME: test_project
  IMAGE_NAME: docker.io/novermore26/test_project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build image with ref tag
        run: docker build -t $IMAGE_NAME:${{ github.ref_name }} .

      - name: Push image with ref tag
        run: docker push $IMAGE_NAME:${{ github.ref_name }}

      - name: Tag and push latest
        run: |
          docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Done message
        run: echo "✅ New $IMAGE_NAME image ready! Version ${{ github.ref_name }}!"
